# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\x05proto\"\x1b\n\x0bPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x08SumReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\rStreamRequest\x12\x0b\n\x03max\x18\x01 \x01(\x05\"\x1c\n\x0bStreamReply\x12\r\n\x05value\x18\x01 \x01(\x05\x32\xa4\x01\n\x0c\x43oreServices\x12,\n\x04Ping\x12\x12.proto.PingRequest\x1a\x10.proto.PingReply\x12)\n\x03Sum\x12\x11.proto.SumRequest\x1a\x0f.proto.SumReply\x12;\n\rStreamNumbers\x12\x14.proto.StreamRequest\x1a\x12.proto.StreamReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=30
  _globals['_PINGREQUEST']._serialized_end=57
  _globals['_PINGREPLY']._serialized_start=59
  _globals['_PINGREPLY']._serialized_end=87
  _globals['_SUMREQUEST']._serialized_start=89
  _globals['_SUMREQUEST']._serialized_end=123
  _globals['_SUMREPLY']._serialized_start=125
  _globals['_SUMREPLY']._serialized_end=151
  _globals['_STREAMREQUEST']._serialized_start=153
  _globals['_STREAMREQUEST']._serialized_end=181
  _globals['_STREAMREPLY']._serialized_start=183
  _globals['_STREAMREPLY']._serialized_end=211
  _globals['_CORESERVICES']._serialized_start=214
  _globals['_CORESERVICES']._serialized_end=378
# @@protoc_insertion_point(module_scope)
