# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/service.proto\x12\x05proto\"\x1b\n\x0bPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\rStreamRequest\x12\x0b\n\x03max\x18\x01 \x01(\x05\"\x1c\n\x0bStreamReply\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1e\n\rUploadRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1d\n\x0cUploadResult\x12\r\n\x05total\x18\x01 \x01(\x05\"\x1b\n\x0b\x43hatMessage\x12\x0c\n\x04text\x18\x01 \x01(\t2\xeb\x01\n\x0c\x43oreServices\x12,\n\x04Ping\x12\x12.proto.PingRequest\x1a\x10.proto.PingReply\x12;\n\rStreamNumbers\x12\x14.proto.StreamRequest\x1a\x12.proto.StreamReply0\x01\x12<\n\rUploadNumbers\x12\x14.proto.UploadRequest\x1a\x13.proto.UploadResult(\x01\x12\x32\n\x04\x43hat\x12\x12.proto.ChatMessage\x1a\x12.proto.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=31
  _globals['_PINGREQUEST']._serialized_end=58
  _globals['_PINGREPLY']._serialized_start=60
  _globals['_PINGREPLY']._serialized_end=88
  _globals['_STREAMREQUEST']._serialized_start=90
  _globals['_STREAMREQUEST']._serialized_end=118
  _globals['_STREAMREPLY']._serialized_start=120
  _globals['_STREAMREPLY']._serialized_end=148
  _globals['_UPLOADREQUEST']._serialized_start=150
  _globals['_UPLOADREQUEST']._serialized_end=180
  _globals['_UPLOADRESULT']._serialized_start=182
  _globals['_UPLOADRESULT']._serialized_end=211
  _globals['_CHATMESSAGE']._serialized_start=213
  _globals['_CHATMESSAGE']._serialized_end=240
  _globals['_CORESERVICES']._serialized_start=243
  _globals['_CORESERVICES']._serialized_end=478
# @@protoc_insertion_point(module_scope)
