# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import service_pb2 as protos_dot_service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServicesStub(object):
    """CoreServices = serviço base do cluster de microserviços.
    Contém exemplos dos 4 tipos de RPC do gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/proto.CoreServices/Ping',
                request_serializer=protos_dot_service__pb2.PingRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.PingReply.FromString,
                _registered_method=True)
        self.StreamNumbers = channel.unary_stream(
                '/proto.CoreServices/StreamNumbers',
                request_serializer=protos_dot_service__pb2.StreamRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.StreamReply.FromString,
                _registered_method=True)
        self.UploadNumbers = channel.stream_unary(
                '/proto.CoreServices/UploadNumbers',
                request_serializer=protos_dot_service__pb2.UploadRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.UploadResult.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/proto.CoreServices/Chat',
                request_serializer=protos_dot_service__pb2.ChatMessage.SerializeToString,
                response_deserializer=protos_dot_service__pb2.ChatMessage.FromString,
                _registered_method=True)


class CoreServicesServicer(object):
    """CoreServices = serviço base do cluster de microserviços.
    Contém exemplos dos 4 tipos de RPC do gRPC.
    """

    def Ping(self, request, context):
        """1️⃣ UNARY RPC
        Uma requisição -> Uma resposta.
        Usado para healthcheck, login, consultas simples e controle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNumbers(self, request, context):
        """2️⃣ SERVER STREAMING RPC
        Uma requisição -> Fluxo contínuo de respostas.
        Usado para progresso, monitoramento, logs, vídeo, resultados contínuos.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadNumbers(self, request_iterator, context):
        """3️⃣ CLIENT STREAMING RPC
        Fluxo de requisições -> Uma resposta final.
        Usado para upload pesado, envio de batches, treinamento ML.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """4️⃣ BIDIRECTIONAL STREAMING RPC
        Fluxo contínuo de requisições <-> Fluxo contínuo de respostas.
        Usado para chat, inferência ML em tempo real, IoT, jogos, trading.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=protos_dot_service__pb2.PingRequest.FromString,
                    response_serializer=protos_dot_service__pb2.PingReply.SerializeToString,
            ),
            'StreamNumbers': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNumbers,
                    request_deserializer=protos_dot_service__pb2.StreamRequest.FromString,
                    response_serializer=protos_dot_service__pb2.StreamReply.SerializeToString,
            ),
            'UploadNumbers': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadNumbers,
                    request_deserializer=protos_dot_service__pb2.UploadRequest.FromString,
                    response_serializer=protos_dot_service__pb2.UploadResult.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=protos_dot_service__pb2.ChatMessage.FromString,
                    response_serializer=protos_dot_service__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.CoreServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.CoreServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreServices(object):
    """CoreServices = serviço base do cluster de microserviços.
    Contém exemplos dos 4 tipos de RPC do gRPC.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.CoreServices/Ping',
            protos_dot_service__pb2.PingRequest.SerializeToString,
            protos_dot_service__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.CoreServices/StreamNumbers',
            protos_dot_service__pb2.StreamRequest.SerializeToString,
            protos_dot_service__pb2.StreamReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadNumbers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/proto.CoreServices/UploadNumbers',
            protos_dot_service__pb2.UploadRequest.SerializeToString,
            protos_dot_service__pb2.UploadResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/proto.CoreServices/Chat',
            protos_dot_service__pb2.ChatMessage.SerializeToString,
            protos_dot_service__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
